CREATE TABLE IF NOT EXISTS UserAdmin(
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS contents(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    location VARCHAR(100) NOT NULL,
    user_id INTEGER REFERENCES UserAdmin(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS files(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    content_id INTEGER REFERENCES contents(id) ON DELETE CASCADE,
    file_path VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS info(
    id SERIAL PRIMARY KEY,
    key VARCHAR(100) NOT NULL,
    value TEXT NOT NULL
);